name: Labeled ERPNext Task

on:
  issues:
    types:
      - labeled

jobs:
  create-task:
    runs-on: ubuntu-latest

    steps:
      - name: Format Payload
        run: |
          echo '{
            "subject": "GH#${{ github.event.issue.number }} - ${{ github.event.issue.title }}",
            "project": "${{ github.event.label.name }}",
            "status": "Open",
            "description": "<p><a href='${{ github.event.issue.html_url }}'>GH#${{ github.event.issue.number }}</a></p>"
            }' > payload.json

      - name: Make API Request to ERPNext
        run: |
          curl -X POST -H "Content-Type: application/json" -H "Authorization: ${{ secrets.WEBHOOK_TOKEN }}" -d @payload.json https://erp.wunderbyte.at/api/resource/Task
